In [1]:
%reset -f
import sys
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
import scipy.special as spec
import matplotlib as mpl
from matplotlib.colors import LogNorm
import matplotlib.cm as cm
import scipy.integrate as integrate
%matplotlib inline

# Set style of plots
ticksize= 12
titlesize = 16
mpl.rcParams.update({'font.size':ticksize }) 
mpl.rcParams.update({'legend.fontsize':ticksize })# legend
mpl.rcParams.update({'ytick.labelsize':ticksize })
mpl.rcParams.update({'xtick.labelsize':ticksize})
mpl.rcParams.update({'axes.titlesize':titlesize})       # Title
mpl.rcParams.update({'axes.labelsize':titlesize})    # x,y,cbar labels
mpl.rcParams.update({'figure.titlesize' :titlesize})
mpl.rcParams.update({'savefig.bbox':'tight'})
mpl.rcParams.update({'axes.formatter.limits':[-4,4]})
mpl.rcParams.update({'figure.figsize':[6,5]})
mpl.rcParams.update({'mathtext.fontset':'cm'})
mpl.rcParams.update({'font.style':'normal'})

pi2 = 2*np.pi

print(sys.version_info)

sys.version_info(major=3, minor=6, micro=1, releaselevel='final', serial=0)


# Make dummy version of PiCOMBI

Need number of bunches.

Need what slots are filled.

Need what slot the beambeam is going to interact with.

In [10]:
nSlots = 10
Slots = np.arange(nSlots)
B1 = np.zeros(nSlots).astype(np.int32)
B1[0:4] = 1
B1with = -np.ones(nSlots).astype(np.int32)



print(Slots)
print(B1)



[0 1 2 3 4 5 6 7 8 9]
[1 1 1 1 0 0 0 0 0 0]


In [9]:
nAct = 5
Actions = np.zeros((5,2))
Actions[:4,0] = 1+np.arange(4)

for i in range(nAct):
    if Actions[i,0] == 1:
        Actions[i,1] = 1
    if Actions[i,0] == 2:
        Actions[i,1] = 1

print('#act | interact with someone')
print(Actions)

#act | interact with someone
[[ 1.  1.]
 [ 2.  1.]
 [ 3.  0.]
 [ 4.  0.]
 [ 0.  0.]]


Can in principle just give an action and slot number, the action will know who it is supposed to interact with. I.e. headon, interact with ...
No... Action need to know where it is!

# Combi style

In [19]:
class action():
    def __init__(self, field1=0, field2=0, field3=0):
        self.field1 = field1
        self.field2 = field2
        self.field3 = field3
        
test = action()
print(test.field2)

0
